"""empty message

Revision ID: 2cdd8494c7af
Revises: 0633ae9f2dfe
Create Date: 2019-12-03 15:48:07.822397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cdd8494c7af'
down_revision = '0633ae9f2dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_calories', sa.Integer(), server_default='2000', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_calories')
    # ### end Alembic commands ###
