"""empty message

Revision ID: 94f33b884491
Revises: 4f1a04198058
Create Date: 2019-12-05 12:04:02.417124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94f33b884491'
down_revision = '4f1a04198058'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_datetime'), 'entry', ['datetime'], unique=False)
    op.create_index(op.f('ix_entry_label'), 'entry', ['label'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entry_label'), table_name='entry')
    op.drop_index(op.f('ix_entry_datetime'), table_name='entry')
    op.drop_table('entry')
    # ### end Alembic commands ###
